server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka

turbine: #监听服务的名称
  app-config: MICROCLOUD-PROVIDER-PRODUCT,MICROCLOUD-PROVIDER-USERS
  cluster-name-expression: new String("default")